name: Copy Assets to Server

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  copy_assets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
   # - name: Install SSH key
   #   uses: webfactory/ssh-agent@v0.5.3
   #   with:
   #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy assets to server
      run: |
        sshpass -p agp6SZ9.9KO0x* rsync -avz -e 'ssh -p 7822' '--exclude='.git' --exclude='.yml' . kindshop@mi3-ts111.a2hosting.com:~/romankagan.com/

