name: Copy Assets to Server

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  copy_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # - name: Install SSH key
      #   uses: webfactory/ssh-agent@v0.5.3
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy assets to server
        run: |
          # Accept the SSH host key for the server
          mkdir -p ~/.ssh
          ssh-keyscan -p 7822 mi3-ts111.a2hosting.com >> ~/.ssh/known_hosts
          # Use sshpass with an environment variable for the SSH password
          sshpass -p ${{ secrets.SSH_PASSWORD }} rsync -avz -e 'ssh -p 7822' --exclude='.git' --exclude='.yml' . ${{ secrets.SSH_PASSWORD }}:~/romankagan.com/
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

